// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhmryertlwcvactnvubm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZobXJ5ZXJ0bHdjdmFjdG52dWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyMTcwMTQsImV4cCI6MjA5MTc5MzAxNH0.yzfBZwZtyndVP9nlqkfspSI-j4-CdKeyTUnJmhdUZYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});