// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neqcosysemavbygcycuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lcWNvc3lzZW1hdmJ5Z2N5Y3VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2NDU1NzYsImV4cCI6MjA5MTIyMTU3Nn0.JlfCS5B8VFooB0uBYzRbqtxcWU9QtSppv4_-iFLY-xU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});